@file:Suppress("ktlint:standard:max-line-length")

package dev.mdwriter.markdown

/**
 * Curated highlighter cases (generated from proto-final on 2026-09-25 and reviewed against CommonMark 0.31.2 / GFM 0.29).
 * expectedSpans == highlighter.spans().joinToString(" ")   (MdSpan.toString format: KIND(arg)[start,end) , arg omitted when 0)
 * expectedLines == (0 until lineCount).joinToString(" ") { lineInfo(it).type.name }
 */
data class HlCase(
    val id: String,
    val input: String,
    val expectedSpans: String,
    val expectedLines: String,
    val note: String,
    val highlight: Boolean = false,
)

val HIGHLIGHTER_CASES =
    listOf(
        HlCase(
            "C1",
            "# Title",
            "HEADING(1)[0,7) HEADING_MARKER[0,2)",
            "ATX_HEADING",
            "ATX H1: HEADING from '#' to EOL; marker incl. space",
        ),
        HlCase(
            "C2",
            "# ",
            "HEADING(1)[0,2) HEADING_MARKER[0,2)",
            "ATX_HEADING",
            "'# ' alone is already a heading (line gets big as soon as '# ' is typed)",
        ),
        HlCase(
            "C3",
            "#",
            "HEADING(1)[0,1) HEADING_MARKER[0,1)",
            "ATX_HEADING",
            "'#' alone = empty H1 (CommonMark)",
        ),
        HlCase(
            "C4",
            "#hashtag not heading",
            "",
            "PARAGRAPH",
            "#hashtag is NOT a heading",
        ),
        HlCase(
            "C5",
            "####### seven",
            "",
            "PARAGRAPH",
            "7 hashes = paragraph",
        ),
        HlCase(
            "C6",
            "## Title ##",
            "HEADING(2)[0,11) HEADING_MARKER[0,3) HEADING_MARKER[9,11)",
            "ATX_HEADING",
            "closing # run is a marker",
        ),
        HlCase(
            "C7",
            "  ### indented",
            "HEADING(3)[2,14) HEADING_MARKER[2,6)",
            "ATX_HEADING",
            "<=3 spaces indent allowed; HEADING starts at first '#'",
        ),
        HlCase(
            "C8",
            "Setext H1\n===",
            "HEADING(1)[0,9) HEADING_MARKER[10,13)",
            "SETEXT_HEADING SETEXT_UNDERLINE",
            "setext H1: content line HEADING, underline = HEADING_MARKER",
            highlight = true,
        ),
        HlCase(
            "C9",
            "Setext H2\n---",
            "HEADING(2)[0,9) HEADING_MARKER[10,13)",
            "SETEXT_HEADING SETEXT_UNDERLINE",
            "setext H2 ('---' under a paragraph is NOT a thematic break)",
        ),
        HlCase(
            "C10",
            "**bold *nested* bold**",
            "STRONG[0,22) EMPHASIS[7,15) EMPHASIS_MARKER[0,2) EMPHASIS_MARKER[7,8) EMPHASIS_MARKER[14,15) EMPHASIS_MARKER[20,22)",
            "PARAGRAPH",
            "nested emphasis inside strong",
        ),
        HlCase(
            "C11",
            "***both***",
            "EMPHASIS[0,10) STRONG[1,9) EMPHASIS_MARKER[0,1) EMPHASIS_MARKER[1,3) EMPHASIS_MARKER[7,9) EMPHASIS_MARKER[9,10)",
            "PARAGRAPH",
            "*** = EMPHASIS(outer) + STRONG(inner), spec order",
        ),
        HlCase(
            "C12",
            "_intra_word_ and snake_case_name",
            "EMPHASIS[0,12) EMPHASIS_MARKER[0,1) EMPHASIS_MARKER[11,12)",
            "PARAGRAPH",
            "'_' intraword does not close; outer _..._ is emphasis",
        ),
        HlCase(
            "C13",
            "foo*bar*baz",
            "EMPHASIS[3,8) EMPHASIS_MARKER[3,4) EMPHASIS_MARKER[7,8)",
            "PARAGRAPH",
            "'*' intraword emphasis IS allowed",
        ),
        HlCase(
            "C14",
            "`code with ** inside` **x**",
            "CODE_SPAN[0,21) STRONG[22,27) CODE_SPAN_MARKER[0,1) CODE_SPAN_MARKER[20,21) EMPHASIS_MARKER[22,24) EMPHASIS_MARKER[25,27)",
            "PARAGRAPH",
            "'**' inside code span is literal; code span markers",
        ),
        HlCase(
            "C15",
            "``a ` b``",
            "CODE_SPAN[0,9) CODE_SPAN_MARKER[0,2) CODE_SPAN_MARKER[7,9)",
            "PARAGRAPH",
            "double-backtick code span containing a single backtick",
        ),
        HlCase(
            "C16",
            "Typing **unclosed bold",
            "",
            "PARAGRAPH",
            "unclosed ** while typing: no styling at all (stays literal)",
        ),
        HlCase(
            "C17",
            "Typing **closed** later *",
            "STRONG[7,17) EMPHASIS_MARKER[7,9) EMPHASIS_MARKER[15,17)",
            "PARAGRAPH",
            "trailing lone '*' ignored",
        ),
        HlCase(
            "C18",
            "~~strike~~ and ~one~",
            "STRIKETHROUGH[0,10) STRIKETHROUGH[15,20) EMPHASIS_MARKER[0,2) EMPHASIS_MARKER[8,10) EMPHASIS_MARKER[15,16) EMPHASIS_MARKER[19,20)",
            "PARAGRAPH",
            "GFM strikethrough ~~x~~ and ~x~",
        ),
        HlCase(
            "C19",
            "==mark== text",
            "HIGHLIGHT[0,8) EMPHASIS_MARKER[0,2) EMPHASIS_MARKER[6,8)",
            "PARAGRAPH",
            "==highlight== (only with enableHighlight=true)",
            highlight = true,
        ),
        HlCase(
            "C20",
            "\\*not emphasis\\* \\# no",
            "ESCAPE_MARKER[0,1) ESCAPE_MARKER[14,15) ESCAPE_MARKER[17,18)",
            "PARAGRAPH",
            "backslash escapes: only the backslash is a marker",
        ),
        HlCase(
            "C21",
            "line one  \nline two\\\nline three",
            "HARD_BREAK[8,10) HARD_BREAK[19,20)",
            "PARAGRAPH PARAGRAPH PARAGRAPH",
            "hard breaks: 2+ trailing spaces, backslash-newline; spans never cross newline",
        ),
        HlCase(
            "C22",
            "[text](http://x.y \"title\")",
            "LINK[0,26) LINK_TEXT[1,5) LINK_URL[7,17) LINK_TITLE[18,25) LINK_MARKER[0,1) LINK_MARKER[5,6) LINK_MARKER[6,7) LINK_MARKER[25,26)",
            "PARAGRAPH",
            "inline link with title: text/url/title/markers",
        ),
        HlCase(
            "C23",
            "![alt](img.png)",
            "LINK(1)[0,15) LINK_TEXT[2,5) LINK_URL[7,14) LINK_MARKER[0,2) LINK_MARKER[5,6) LINK_MARKER[6,7) LINK_MARKER[14,15)",
            "PARAGRAPH",
            "image: arg=1, '![' marker",
        ),
        HlCase(
            "C24",
            "[ref][r] and [r]\n\n[r]: https://e.com \"T\"",
            "LINK[0,8) LINK_TEXT[1,4) LINK_LABEL[6,7) LINK[13,16) LINK_TEXT[14,15) LINK_DEF[18,40) LINK_LABEL[19,20) LINK_URL[23,36) LINK_TITLE[37,40) LINK_MARKER[0,1) LINK_MARKER[4,5) LINK_MARKER[5,6) LINK_MARKER[7,8) LINK_MARKER[13,14) LINK_MARKER[15,16) LINK_MARKER[18,19) LINK_MARKER[20,22)",
            "PARAGRAPH BLANK LINK_DEF",
            "full + shortcut reference links resolve only because [r] is defined; LINK_DEF line",
        ),
        HlCase(
            "C25",
            "[undefined ref]",
            "",
            "PARAGRAPH",
            "undefined reference is plain text",
        ),
        HlCase(
            "C26",
            "<https://auto.link> www.example.com https://bare.url/p. mail me@x.org",
            "AUTOLINK[0,19) LINK_URL[1,18) AUTOLINK[20,35) AUTOLINK[36,54) AUTOLINK[61,69) LINK_MARKER[0,1) LINK_MARKER[18,19)",
            "PARAGRAPH",
            "<autolink>, www., https:// with trailing '.' trimmed, bare e-mail",
        ),
        HlCase(
            "C27",
            "Footnote[^1].\n\n[^1]: The note.",
            "FOOTNOTE_REF[8,12) FOOTNOTE_REF(1)[15,19) LINK_MARKER[19,20)",
            "PARAGRAPH BLANK FOOTNOTE_DEF",
            "footnote ref + footnote definition label (arg=1)",
        ),
        HlCase(
            "C28",
            "&amp; &#123; &notanentity",
            "ENTITY[0,5) ENTITY[6,12)",
            "PARAGRAPH",
            "named/numeric entities; '&notanentity' without ';' is text",
        ),
        HlCase(
            "C29",
            "text <span>inline</span> <!-- c -->",
            "HTML_INLINE[5,11) HTML_INLINE[17,24) HTML_INLINE[25,35)",
            "PARAGRAPH",
            "inline HTML tags and comment",
        ),
        HlCase(
            "C30",
            "<!-- block\ncomment -->\nafter",
            "HTML_BLOCK(2)[0,10) HTML_BLOCK(2)[11,22)",
            "HTML HTML PARAGRAPH",
            "HTML block type 2 (comment) spans 2 lines; next line is paragraph",
        ),
        HlCase(
            "C31",
            "- item\n- [ ] task\n- [x] done",
            "LIST_MARKER[0,1) LIST_MARKER[7,8) TASK_MARKER[9,12) LIST_MARKER[18,19) TASK_MARKER(1)[20,23)",
            "PARAGRAPH PARAGRAPH PARAGRAPH",
            "bullet list + GFM task items (arg=1 checked); contentStart after '[ ] '",
        ),
        HlCase(
            "C32",
            "1) one\n2) two",
            "LIST_MARKER[0,2) LIST_MARKER[7,9)",
            "PARAGRAPH PARAGRAPH",
            "'1)' ordered list",
        ),
        HlCase(
            "C33",
            "3. three",
            "LIST_MARKER[0,2)",
            "PARAGRAPH",
            "ordered list starting at 3 (not after a paragraph)",
        ),
        HlCase(
            "C34",
            "- a\n  - b\n    - c",
            "LIST_MARKER[0,1) LIST_MARKER(1)[6,7) LIST_MARKER(2)[14,15)",
            "PARAGRAPH PARAGRAPH PARAGRAPH",
            "nested lists: LIST_MARKER arg = depth",
        ),
        HlCase(
            "C35",
            "- item\n\n      indented code in item",
            "CODE_BLOCK[14,35) LIST_MARKER[0,1)",
            "PARAGRAPH BLANK INDENTED_CODE",
            "indented code inside a list item (content column + 4)",
        ),
        HlCase(
            "C36",
            "- item\ncontinued lazily",
            "LIST_MARKER[0,1)",
            "PARAGRAPH PARAGRAPH",
            "lazy continuation keeps the list container (listDepth=1)",
        ),
        HlCase(
            "C37",
            "    indented code",
            "CODE_BLOCK[4,17)",
            "INDENTED_CODE",
            "top-level indented code",
        ),
        HlCase(
            "C38",
            "> quote **b**\n> > nested\nlazy",
            "BLOCKQUOTE(1)[0,13) STRONG[8,13) BLOCKQUOTE(2)[14,24) BLOCKQUOTE(2)[25,29) QUOTE_MARKER[0,2) EMPHASIS_MARKER[8,10) EMPHASIS_MARKER[11,13) QUOTE_MARKER[14,16) QUOTE_MARKER[16,18)",
            "PARAGRAPH PARAGRAPH PARAGRAPH",
            "quote with inline, nested quote, lazy line keeps depth 2",
        ),
        HlCase(
            "C39",
            "```kotlin\nval x = 1\n```",
            "CODE_INFO[3,9) CODE_BLOCK[10,19) CODE_FENCE[0,3) CODE_FENCE[20,23)",
            "FENCE_OPEN FENCED_CODE FENCE_CLOSE",
            "fenced code with info string",
        ),
        HlCase(
            "C40",
            "```\nunclosed\nfence",
            "CODE_BLOCK[4,12) CODE_BLOCK[13,18) CODE_FENCE[0,3)",
            "FENCE_OPEN FENCED_CODE FENCED_CODE",
            "unclosed fence runs to end of document",
        ),
        HlCase(
            "C41",
            "~~~\n`~~~` inside\n~~~",
            "CODE_BLOCK[4,16) CODE_FENCE[0,3) CODE_FENCE[17,20)",
            "FENCE_OPEN FENCED_CODE FENCE_CLOSE",
            "tilde fence; backticks inside are code",
        ),
        HlCase(
            "C42",
            "| a | b |\n|:--|--:|\n| 1 | `|` |",
            "TABLE_ROW[0,9) TABLE_ROW(1)[10,19) TABLE_ROW(2)[20,31) TABLE_PIPE[0,1) TABLE_PIPE[4,5) TABLE_PIPE[8,9) TABLE_PIPE[10,11) TABLE_PIPE[14,15) TABLE_PIPE[18,19) TABLE_PIPE[20,21) TABLE_PIPE[24,25) TABLE_PIPE[27,28) TABLE_PIPE[30,31)",
            "TABLE_HEADER TABLE_DELIMITER TABLE_ROW",
            "GFM table: header/delimiter/body rows; the pipe inside backticks is a cell separator (GFM)",
        ),
        HlCase(
            "C43",
            "| not | table |\nno delimiter row",
            "",
            "PARAGRAPH PARAGRAPH",
            "no delimiter row -> not a table",
        ),
        HlCase(
            "C44",
            "---\ntitle: Hello\n---\n# Body",
            "FRONT_MATTER[4,16) HEADING(1)[21,27) FRONT_MATTER_FENCE[0,3) FRONT_MATTER_FENCE[17,20) HEADING_MARKER[21,23)",
            "FRONT_MATTER_FENCE FRONT_MATTER FRONT_MATTER_FENCE ATX_HEADING",
            "YAML front matter (closed) then heading",
        ),
        HlCase(
            "C45",
            "---\nnot front matter (no close)",
            "THEMATIC_BREAK[0,3)",
            "THEMATIC_BREAK PARAGRAPH",
            "'---' without closing fence = thematic break, not front matter",
        ),
        HlCase(
            "C46",
            "***\n- - -",
            "THEMATIC_BREAK[0,3) THEMATIC_BREAK[4,9)",
            "THEMATIC_BREAK THEMATIC_BREAK",
            "thematic breaks *** and - - -",
        ),
        HlCase(
            "C47",
            "a\n***\nb",
            "THEMATIC_BREAK[2,5)",
            "PARAGRAPH THEMATIC_BREAK PARAGRAPH",
            "*** interrupts a paragraph",
        ),
        HlCase(
            "C48",
            "Para\n    not code (lazy)",
            "",
            "PARAGRAPH PARAGRAPH",
            "indented line after a paragraph is lazy text, not code",
        ),
        HlCase(
            "C49",
            "*a\nb*",
            "EMPHASIS[0,2) EMPHASIS[3,5) EMPHASIS_MARKER[0,1) EMPHASIS_MARKER[4,5)",
            "PARAGRAPH PARAGRAPH",
            "emphasis across a soft line break is split per line",
        ),
        HlCase(
            "C50",
            "<div>\n**not styled**\n</div>\n\n**styled**",
            "HTML_BLOCK(6)[0,5) HTML_BLOCK(6)[6,20) HTML_BLOCK(6)[21,27) STRONG[29,39) EMPHASIS_MARKER[29,31) EMPHASIS_MARKER[37,39)",
            "HTML HTML HTML BLANK PARAGRAPH",
            "HTML block type 6 (<div>) until blank line: inner ** not styled",
        ),
    )

/** Type [typed] one char at a time at [at] using update(text, pos, 0, 1). After EVERY step: incremental spans == fullScan spans.
 * stepSpans[i] = expected spans().joinToString(" ") after typing i+1 chars; stepFull[i] = expected HighlightDelta.full. */
data class TypingCase(
    val id: String,
    val start: String,
    val at: Int,
    val typed: String,
    val stepSpans: List<String>,
    val stepFull: List<Boolean>,
)

val TYPING_CASES =
    listOf(
        TypingCase(
            "T1",
            "",
            0,
            "# Hi",
            listOf(
                "HEADING(1)[0,1) HEADING_MARKER[0,1)",
                "HEADING(1)[0,2) HEADING_MARKER[0,2)",
                "HEADING(1)[0,3) HEADING_MARKER[0,2)",
                "HEADING(1)[0,4) HEADING_MARKER[0,2)",
            ),
            listOf(false, false, false, false),
        ),
        TypingCase(
            "T2",
            "a ",
            2,
            "**b**",
            listOf(
                "",
                "",
                "",
                "EMPHASIS[3,6) EMPHASIS_MARKER[3,4) EMPHASIS_MARKER[5,6)",
                "STRONG[2,7) EMPHASIS_MARKER[2,4) EMPHASIS_MARKER[5,7)",
            ),
            listOf(false, false, false, false, false),
        ),
        TypingCase(
            "T3",
            "x\n\ny",
            1,
            "\n```",
            listOf("", "", "", "CODE_BLOCK[7,8) CODE_FENCE[2,5)"),
            listOf(false, false, false, false),
        ),
        TypingCase(
            "T4",
            "Title\n",
            6,
            "==",
            listOf("HEADING(1)[0,5) HEADING_MARKER[6,7)", "HEADING(1)[0,5) HEADING_MARKER[6,8)"),
            listOf(false, false),
        ),
        TypingCase(
            "T5",
            "| a | b |\n",
            10,
            "|-|-|",
            listOf(
                "",
                "",
                "",
                "TABLE_ROW[0,9) TABLE_ROW(1)[10,14) TABLE_PIPE[0,1) TABLE_PIPE[4,5) TABLE_PIPE[8,9) TABLE_PIPE[10,11) TABLE_PIPE[12,13)",
                "TABLE_ROW[0,9) TABLE_ROW(1)[10,15) TABLE_PIPE[0,1) TABLE_PIPE[4,5) TABLE_PIPE[8,9) TABLE_PIPE[10,11) TABLE_PIPE[12,13) TABLE_PIPE[14,15)",
            ),
            listOf(false, false, false, false, false),
        ),
        TypingCase(
            "T6",
            "[r]\n\n",
            5,
            "[r]: u",
            listOf(
                "",
                "",
                "",
                "",
                "",
                "LINK[0,3) LINK_TEXT[1,2) LINK_DEF[5,11) LINK_LABEL[6,7) LINK_URL[10,11) LINK_MARKER[0,1) LINK_MARKER[2,3) LINK_MARKER[5,6) LINK_MARKER[7,9)",
            ),
            listOf(false, false, false, false, false, true),
        ),
        TypingCase(
            "T7",
            "",
            0,
            "- [x] t",
            listOf(
                "LIST_MARKER[0,1)",
                "LIST_MARKER[0,1)",
                "LIST_MARKER[0,1)",
                "LIST_MARKER[0,1)",
                "LIST_MARKER[0,1) TASK_MARKER(1)[2,5)",
                "LIST_MARKER[0,1) TASK_MARKER(1)[2,5)",
                "LIST_MARKER[0,1) TASK_MARKER(1)[2,5)",
            ),
            listOf(false, false, false, false, false, false, false),
        ),
    )
